-- Hour Craft Path agreement coverage seed, reviewed 2026-07-26.
--
-- This migration adds:
--   * 30 catalog entries from the documented minimum scope;
--   * 5 source-verified but deliberately non-implemented versions;
--   * 5 byte-verified official main-agreement sources.
--
-- It deliberately adds no agreement_rules or agreement_rate_periods. No
-- agreement is active, no rate is inferred, and no unverified local PDF is
-- promoted to legal evidence. INSERT OR IGNORE makes the additive seed safe to
-- re-run without rewriting immutable source history.

PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO agreements (
  id,
  catalog_key,
  exact_title,
  agreement_parties,
  employer_organization,
  covered_work_areas,
  employee_category,
  geography_scope,
  catalog_status
) VALUES
  (
    'agr_ba_di_3f',
    'bygge-anlaeg-di-3f',
    'Bygge- og Anlægsoverenskomsten 2025-2028',
    'DI Overenskomst III og 3F Fagligt Fælles Forbund',
    'DI Overenskomst III',
    'Bygge- og anlægsarbejde; konkret fagligt scope kræver assignment-verifikation',
    'Voksne timelønnede inden for aftalens dokumenterede scope',
    'Kildens dækningsområde; konkrete undtagelser kræver manuel afklaring',
    'verified_not_implemented'
  ),
  (
    'agr_bygning',
    'bygningsoverenskomsten',
    'Bygningsoverenskomsten 2025-2028',
    'DI Overenskomst III og 3F Fagligt Fælles Forbund',
    'DI Overenskomst III',
    'Bygningsarbejde; konkret fagligt scope kræver assignment-verifikation',
    'Voksne timelønnede inden for aftalens dokumenterede scope',
    'Kildens dækningsområde; konkrete undtagelser kræver manuel afklaring',
    'verified_not_implemented'
  ),
  (
    'agr_murer',
    'murer-murerarbejdsmand',
    'Overenskomst for murer- og murerarbejdsmandsarbejde 2025-2028',
    'DI Overenskomst III og 3F Fagligt Fælles Forbund',
    'DI Overenskomst III',
    'Murer- og murerarbejdsmandsarbejde; konkret fagligt scope kræver assignment-verifikation',
    'Voksne timelønnede inden for aftalens dokumenterede scope',
    'Kildens dækningsområde; København/Frederiksberg kræver særskilt afklaring',
    'verified_not_implemented'
  ),
  (
    'agr_gulv',
    'gulvoverenskomsten',
    'Gulvoverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Gulvarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret; BJMF-protokol skal undersøges særskilt',
    'manual_review_required'
  ),
  (
    'agr_asfalt',
    'asfaltoverenskomsten',
    'Asfaltoverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Asfaltarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_isolering',
    'isoleringsoverenskomsten',
    'Isoleringsoverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Isoleringsarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_glas',
    'glasoverenskomsten',
    'Glasoverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Glasarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_ba_dansk_haandvaerk',
    'bygge-anlaeg-dansk-haandvaerk-3f',
    'Dansk Håndværk/3F Bygge- og Anlægsoverenskomst (arbejdstitel; officiel titel ikke verificeret)',
    'Dansk Håndværk og 3F ifølge minimumslisten; eksakte partsnavne ikke verificeret',
    'Dansk Håndværk ifølge minimumslisten',
    'Bygge- og anlægsarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_el_di_def',
    'el-di-def',
    'El-overenskomsten mellem DI og Dansk El-Forbund (arbejdstitel; officiel titel ikke verificeret)',
    'DI og Dansk El-Forbund ifølge minimumslisten; præcis DI-enhed ikke verificeret',
    'DI-enhed ikke verificeret',
    'El-arbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_elektriker_tekniq_def',
    'elektrikeroverenskomsten-tekniq-def',
    'Elektrikeroverenskomsten 2025-2028',
    'TEKNIQ Arbejdsgiverne og Dansk El-Forbund',
    'TEKNIQ Arbejdsgiverne',
    'Elektrikerarbejde; konkret fagligt scope kræver assignment-verifikation',
    'Voksne timelønnede inden for aftalens dokumenterede scope',
    'Kildens dækningsområde; konkrete undtagelser kræver manuel afklaring',
    'verified_not_implemented'
  ),
  (
    'agr_metal_blik_roer',
    'metal-blik-roer',
    'Metal- og Blik- og Røroverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Metal-, blik- og rørarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_vvs_tekniq_blikroer_metal',
    'vvs-tekniq-blikroer-metal',
    'VVS-overenskomsten mellem TEKNIQ, Blik & Rør og Dansk Metal (arbejdstitel; officiel titel ikke verificeret)',
    'TEKNIQ, Blik & Rør og Dansk Metal ifølge minimumslisten; eksakte partsnavne ikke verificeret',
    'TEKNIQ-enhed ikke verificeret',
    'VVS-, blik- og rørarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'source_conflict'
  ),
  (
    'agr_maler_di',
    'maler-di-malerforbundet',
    'Maleroverenskomsten mellem DI og Malerforbundet (arbejdstitel; officiel titel ikke verificeret)',
    'DI og Malerforbundet ifølge minimumslisten; præcis DI-enhed og partsnavne ikke verificeret',
    'DI-enhed ikke verificeret',
    'Malerarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret; geografiske prislister mangler',
    'source_conflict'
  ),
  (
    'agr_maler_danske_malermestre',
    'maler-danske-malermestre',
    'Maleroverenskomsten mellem Danske Malermestre og Malerforbundet (arbejdstitel; officiel titel ikke verificeret)',
    'Danske Malermestre og Malerforbundet ifølge minimumslisten; eksakte partsnavne ikke verificeret',
    'Danske Malermestre ifølge minimumslisten',
    'Malerarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret; geografiske prislister mangler',
    'source_conflict'
  ),
  (
    'agr_maler_kooperationen',
    'maler-kooperationen',
    'Kooperationens maleroverenskomst (arbejdstitel; officiel titel ikke verificeret)',
    'Kooperationen og Malerforbundet ifølge minimumslistens titel; eksakte partsnavne ikke verificeret',
    'Kooperationen ifølge minimumslistens titel',
    'Malerarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret; geografiske prislister mangler',
    'source_conflict'
  ),
  (
    'agr_jord_beton_kbh',
    'jord-beton-kbh-frederiksberg-amager',
    'Jord- og Betonoverenskomsten for København, Frederiksberg og Amager (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Jord- og betonarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'København, Frederiksberg og Amager ifølge minimumslisten; præcis afgrænsning ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_murerarbejdsmand_kbh',
    'murerarbejdsmand-kbh-frederiksberg',
    'Murerarbejdsmandsoverenskomsten for København og Frederiksberg (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Murerarbejdsmandsarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'København og Frederiksberg ifølge minimumslisten',
    'missing_official_source'
  ),
  (
    'agr_source_gulv_bjmf',
    'gulv-bjmf-protokol',
    'Geografisk BJMF-protokol til Gulvoverenskomsten (ledsagende kilde; officiel titel ikke verificeret)',
    'Ikke verificeret; ikke et selvstændigt overenskomstvalg',
    '',
    'Ledsagende geografisk protokol til Gulvoverenskomsten',
    'Følger en fremtidig verificeret Gulvoverenskomst-version',
    'Ikke verificeret',
    'out_of_scope'
  ),
  (
    'agr_industriens',
    'industriens-overenskomst',
    'Industriens Overenskomst 2025-2028',
    'DI Overenskomst I og CO-industri',
    'DI Overenskomst I',
    'Industriarbejde; konkret fagligt scope kræver assignment-verifikation',
    'Voksne timelønnede inden for aftalens dokumenterede scope',
    'Kildens dækningsområde; konkrete undtagelser kræver manuel afklaring',
    'verified_not_implemented'
  ),
  (
    'agr_source_industriens_org',
    'industriens-organisationsaftaler',
    'Industriens Organisationsaftaler (ledsagende kilde; officiel titel ikke verificeret)',
    'Skal følge parterne til Industriens Overenskomst; separat dokumentidentitet ikke verificeret',
    '',
    'Ledsagende regelkilde til Industriens Overenskomst',
    'Følger en verificeret Industriens Overenskomst-version',
    'Følger hovedaftalens dokumenterede scope',
    'out_of_scope'
  ),
  (
    'agr_industrioverenskomst_di_byggeri',
    'industrioverenskomsten-di-byggeri',
    'Industrioverenskomsten under DI Byggeri (arbejdstitel; officiel titel ikke verificeret)',
    'DI Byggeri ifølge minimumslisten; fulde aftaleparter ikke verificeret',
    'DI Byggeri ifølge minimumslisten',
    'Industriarbejde under aftalens eget scope; må ikke sammenlægges med Industriens Overenskomst',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_trae_moebel',
    'trae-moebeloverenskomsten',
    'Træ- og Møbeloverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Træ- og møbelarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_industri_trae_moebel',
    'industri-trae-moebeloverenskomsten',
    'Industri-, Træ- og Møbeloverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Industri-, træ- og møbelarbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_emballage',
    'emballageindustriens-overenskomst',
    'Emballageindustriens Overenskomst (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Emballageindustri; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_foedevare',
    'foedevareindustrielle-overenskomst',
    'Den Fødevareindustrielle Overenskomst (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Fødevareindustri; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_slagte',
    'slagteoverenskomsten',
    'Slagteoverenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Slagteriområdet; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_mejeri',
    'mejeribranchens-faellesoverenskomst',
    'Mejeribranchens Fællesoverenskomst (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Mejeribranchen; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_industri_vvs',
    'industri-vvs-overenskomsten',
    'Industri- og VVS-overenskomsten (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Industri- og VVS-arbejde; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'manual_review_required'
  ),
  (
    'agr_dsm_industri',
    'dsm-industriomraadet',
    'DSM Industriområdet (arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'DSM-industriområdet; fagligt scope ikke verificeret',
    'Voksne timelønnede; præcis kategori ikke verificeret',
    'Ikke verificeret',
    'missing_official_source'
  ),
  (
    'agr_faglaerte_betinget',
    'faglaerteoverenskomsten-betinget',
    'Faglærteoverenskomsten (betinget arbejdstitel; officiel titel ikke verificeret)',
    'Ikke verificeret',
    '',
    'Kun relevant hvis en eksisterende virksomhed dokumenteret er omfattet',
    'Voksne timelønnede; præcis faglært kategori ikke verificeret',
    'Ikke verificeret',
    'out_of_scope'
  );

INSERT OR IGNORE INTO agreement_versions (
  id,
  agreement_id,
  version_label,
  valid_from,
  valid_to,
  published_at,
  rule_schema_version,
  implementation_status,
  verification_status,
  activated_at,
  activated_by_membership_id
) VALUES
  (
    'agrv_ba_di_3f_2025_2028',
    'agr_ba_di_3f',
    '2025-2028',
    '2025-03-01',
    NULL,
    NULL,
    1,
    'not_implemented',
    'verified_not_implemented',
    NULL,
    NULL
  ),
  (
    'agrv_bygning_2025_2028',
    'agr_bygning',
    '2025-2028',
    '2025-03-01',
    NULL,
    NULL,
    1,
    'not_implemented',
    'verified_not_implemented',
    NULL,
    NULL
  ),
  (
    'agrv_murer_2025_2028',
    'agr_murer',
    '2025-2028',
    '2025-03-01',
    NULL,
    NULL,
    1,
    'not_implemented',
    'verified_not_implemented',
    NULL,
    NULL
  ),
  (
    'agrv_elektriker_2025_2028',
    'agr_elektriker_tekniq_def',
    '2025-2028',
    '2025-03-01',
    NULL,
    NULL,
    1,
    'not_implemented',
    'verified_not_implemented',
    NULL,
    NULL
  ),
  (
    'agrv_industriens_2025_2028',
    'agr_industriens',
    '2025-2028',
    '2025-03-01',
    NULL,
    NULL,
    1,
    'not_implemented',
    'verified_not_implemented',
    NULL,
    NULL
  );

INSERT OR IGNORE INTO agreement_sources (
  id,
  agreement_version_id,
  source_type,
  official_url,
  document_title,
  agreement_parties,
  document_version,
  valid_from,
  valid_to,
  retrieved_at,
  source_sha256,
  paragraph_reference,
  page_reference,
  table_reference,
  private_storage_object_key,
  verification_status,
  verified_at,
  verified_by_membership_id
) VALUES
  (
    'agrsrc_ba_di_3f_main_2025_2028',
    'agrv_ba_di_3f_2025_2028',
    'main_agreement',
    'https://www.3f.dk/-/media/files/artikler/overenskomst/byggegruppen/overenskomster/bygge--og-anlaegsoverenskomsten-2025-2028.pdf',
    'Bygge- og Anlægsoverenskomsten 2025-2028',
    'DI Overenskomst III og 3F Fagligt Fælles Forbund',
    '2025-2028; official PDF hash verified 2026-07-26',
    '2025-03-01',
    NULL,
    '2026-07-26T00:00:00Z',
    '82dc8294ee76d127bcf979be5fc5afa6e0db531d581e158480be529374359f84',
    '§ 107',
    'Trykt side 133; fysisk PDF-side 135 (1-baseret)',
    '',
    'legal-sources/overenskomster/bygge-anlaegsoverenskomsten.pdf',
    'verified_not_implemented',
    '2026-07-26T00:00:00Z',
    NULL
  ),
  (
    'agrsrc_bygning_main_2025_2028',
    'agrv_bygning_2025_2028',
    'main_agreement',
    'https://www.3f.dk/-/media/files/artikler/overenskomst/byggegruppen/overenskomster/bygningsoverenskomsten-2025-2028_002.pdf',
    'Bygningsoverenskomsten 2025-2028',
    'DI Overenskomst III og 3F Fagligt Fælles Forbund',
    '2025-2028; official PDF file variant 002 hash verified 2026-07-26',
    '2025-03-01',
    NULL,
    '2026-07-26T00:00:00Z',
    'c680cae31338113c01a51942288c16eeec581dd54c450b08172c7ed650768c0c',
    '§ 84',
    'Trykt side 123; fysisk PDF-side 125 (1-baseret)',
    '',
    'legal-sources/overenskomster/bygningsoverenskomsten.pdf',
    'verified_not_implemented',
    '2026-07-26T00:00:00Z',
    NULL
  ),
  (
    'agrsrc_murer_main_2025_2028',
    'agrv_murer_2025_2028',
    'main_agreement',
    'https://www.3f.dk/-/media/files/artikler/overenskomst/byggegruppen/overenskomster/murer--og-murerarbejdsmandsarbejde-dio-iii-2025-2028.pdf',
    'Overenskomst for murer- og murerarbejdsmandsarbejde 2025-2028',
    'DI Overenskomst III og 3F Fagligt Fælles Forbund',
    '2025-2028; official PDF hash verified 2026-07-26',
    '2025-03-01',
    NULL,
    '2026-07-26T00:00:00Z',
    '0b5e78b1fbbaabffeb76042d1970b502028edf4263fc7667c57742f4b4fe3b07',
    '§ 86',
    'Trykt side 118-119; fysisk PDF-side 122-123 (1-baseret)',
    '',
    'legal-sources/overenskomster/murer-murerarbejdsmandsarbejde.pdf',
    'verified_not_implemented',
    '2026-07-26T00:00:00Z',
    NULL
  ),
  (
    'agrsrc_elektriker_main_2025_2028',
    'agrv_elektriker_2025_2028',
    'main_agreement',
    'https://www.tekniq.dk/media/pwjbybrp/elektrikeroverenskomst-2025-2028.pdf',
    'Elektrikeroverenskomsten 2025-2028',
    'TEKNIQ Arbejdsgiverne og Dansk El-Forbund',
    '2025-2028; official PDF hash verified 2026-07-26',
    '2025-03-01',
    NULL,
    '2026-07-26T00:00:00Z',
    'c7dba83a52bff770e12b2e835ad4032101d1aeb72381f5c9255c4faf0e5f1f3c',
    '§ 21',
    'Trykt side 103; fysisk PDF-side 103 (1-baseret)',
    '',
    'legal-sources/overenskomster/elektrikeroverenskomsten.pdf',
    'verified_not_implemented',
    '2026-07-26T00:00:00Z',
    NULL
  ),
  (
    'agrsrc_industriens_main_2025_2028',
    'agrv_industriens_2025_2028',
    'main_agreement',
    'https://www.co-industri.dk/sites/default/files/2025-08/Industriens-Overenskomst-2025-2028-2025_07_31.pdf',
    'Industriens Overenskomst 2025-2028',
    'DI Overenskomst I og CO-industri',
    '2025-2028; corrected PDF 2025-07-31 hash verified 2026-07-26',
    '2025-03-01',
    NULL,
    '2026-07-26T00:00:00Z',
    'eb9971928f9bfe3ad12ea3aca15cae806e583d160032d8cbef34b605d26780e0',
    '§ 50',
    'Trykt side 128; fysisk PDF-side 129 (1-baseret)',
    '',
    'legal-sources/overenskomster/industriens-overenskomst.pdf',
    'verified_not_implemented',
    '2026-07-26T00:00:00Z',
    NULL
  );
