name = "hour-craft-timesheet-mail"
main = "src/index.ts"
compatibility_date = "2026-06-28"

[vars]
ADMIN_EMAIL = "mathiasfriisandersen@gmail.com"
ALLOWED_ORIGIN = "https://mathiasfriisandersen.dk"
RESEND_FROM_EMAIL = "Sub-Z Timesheet <timesheet@send.mathiasfriisandersen.dk>"
