name = "hour-craft-timesheet-mail"
main = "src/index.ts"
compatibility_date = "2026-06-28"

[vars]
ALLOWED_ORIGIN = "https://mathiasfriisandersen.dk,http://127.0.0.1:8081,http://localhost:8081,http://127.0.0.1:8080,http://localhost:8080"
APP_BASE_URL = "https://mathiasfriisandersen.dk/hour-craft-path"
RESEND_FROM_EMAIL = "Sub-Z Timesheet <timesheet@send.mathiasfriisandersen.dk>"

[[d1_databases]]
binding = "TIMESHEET_DB"
database_name = "mathias_andersen"
database_id = "2aa37479-6b01-4749-9ed1-38a5650c075f"
