/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VikarIndexRouteImport } from './routes/vikar.index'
import { Route as KontaktpersonIndexRouteImport } from './routes/kontaktperson.index'
import { Route as Bruger2IndexRouteImport } from './routes/bruger2.index'
import { Route as Bruger1IndexRouteImport } from './routes/bruger1.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VikarInviteRouteImport } from './routes/vikar.invite'
import { Route as VikarConsentRouteImport } from './routes/vikar.consent'
import { Route as VikarIdRouteImport } from './routes/vikar.$id'
import { Route as KontaktpersonInviteRouteImport } from './routes/kontaktperson.invite'
import { Route as KontaktpersonIdRouteImport } from './routes/kontaktperson.$id'
import { Route as Bruger2WorkersRouteImport } from './routes/bruger2.workers'
import { Route as Bruger1WorkersRouteImport } from './routes/bruger1.workers'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminCreateWorkerRouteImport } from './routes/admin.create-worker'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VikarIndexRoute = VikarIndexRouteImport.update({
  id: '/vikar/',
  path: '/vikar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktpersonIndexRoute = KontaktpersonIndexRouteImport.update({
  id: '/kontaktperson/',
  path: '/kontaktperson/',
  getParentRoute: () => rootRouteImport,
} as any)
const Bruger2IndexRoute = Bruger2IndexRouteImport.update({
  id: '/bruger2/',
  path: '/bruger2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Bruger1IndexRoute = Bruger1IndexRouteImport.update({
  id: '/bruger1/',
  path: '/bruger1/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VikarInviteRoute = VikarInviteRouteImport.update({
  id: '/vikar/invite',
  path: '/vikar/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const VikarConsentRoute = VikarConsentRouteImport.update({
  id: '/vikar/consent',
  path: '/vikar/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const VikarIdRoute = VikarIdRouteImport.update({
  id: '/vikar/$id',
  path: '/vikar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktpersonInviteRoute = KontaktpersonInviteRouteImport.update({
  id: '/kontaktperson/invite',
  path: '/kontaktperson/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktpersonIdRoute = KontaktpersonIdRouteImport.update({
  id: '/kontaktperson/$id',
  path: '/kontaktperson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Bruger2WorkersRoute = Bruger2WorkersRouteImport.update({
  id: '/bruger2/workers',
  path: '/bruger2/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const Bruger1WorkersRoute = Bruger1WorkersRouteImport.update({
  id: '/bruger1/workers',
  path: '/bruger1/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/admin/workers',
  path: '/admin/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateWorkerRoute = AdminCreateWorkerRouteImport.update({
  id: '/admin/create-worker',
  path: '/admin/create-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/create-worker': typeof AdminCreateWorkerRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/workers': typeof AdminWorkersRoute
  '/bruger1/workers': typeof Bruger1WorkersRoute
  '/bruger2/workers': typeof Bruger2WorkersRoute
  '/kontaktperson/$id': typeof KontaktpersonIdRoute
  '/kontaktperson/invite': typeof KontaktpersonInviteRoute
  '/vikar/$id': typeof VikarIdRoute
  '/vikar/consent': typeof VikarConsentRoute
  '/vikar/invite': typeof VikarInviteRoute
  '/admin/': typeof AdminIndexRoute
  '/bruger1/': typeof Bruger1IndexRoute
  '/bruger2/': typeof Bruger2IndexRoute
  '/kontaktperson/': typeof KontaktpersonIndexRoute
  '/vikar/': typeof VikarIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/create-worker': typeof AdminCreateWorkerRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/workers': typeof AdminWorkersRoute
  '/bruger1/workers': typeof Bruger1WorkersRoute
  '/bruger2/workers': typeof Bruger2WorkersRoute
  '/kontaktperson/$id': typeof KontaktpersonIdRoute
  '/kontaktperson/invite': typeof KontaktpersonInviteRoute
  '/vikar/$id': typeof VikarIdRoute
  '/vikar/consent': typeof VikarConsentRoute
  '/vikar/invite': typeof VikarInviteRoute
  '/admin': typeof AdminIndexRoute
  '/bruger1': typeof Bruger1IndexRoute
  '/bruger2': typeof Bruger2IndexRoute
  '/kontaktperson': typeof KontaktpersonIndexRoute
  '/vikar': typeof VikarIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/create-worker': typeof AdminCreateWorkerRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/workers': typeof AdminWorkersRoute
  '/bruger1/workers': typeof Bruger1WorkersRoute
  '/bruger2/workers': typeof Bruger2WorkersRoute
  '/kontaktperson/$id': typeof KontaktpersonIdRoute
  '/kontaktperson/invite': typeof KontaktpersonInviteRoute
  '/vikar/$id': typeof VikarIdRoute
  '/vikar/consent': typeof VikarConsentRoute
  '/vikar/invite': typeof VikarInviteRoute
  '/admin/': typeof AdminIndexRoute
  '/bruger1/': typeof Bruger1IndexRoute
  '/bruger2/': typeof Bruger2IndexRoute
  '/kontaktperson/': typeof KontaktpersonIndexRoute
  '/vikar/': typeof VikarIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/$id'
    | '/admin/calendar'
    | '/admin/companies'
    | '/admin/create-worker'
    | '/admin/rules'
    | '/admin/statistics'
    | '/admin/users'
    | '/admin/workers'
    | '/bruger1/workers'
    | '/bruger2/workers'
    | '/kontaktperson/$id'
    | '/kontaktperson/invite'
    | '/vikar/$id'
    | '/vikar/consent'
    | '/vikar/invite'
    | '/admin/'
    | '/bruger1/'
    | '/bruger2/'
    | '/kontaktperson/'
    | '/vikar/'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$id'
    | '/admin/calendar'
    | '/admin/companies'
    | '/admin/create-worker'
    | '/admin/rules'
    | '/admin/statistics'
    | '/admin/users'
    | '/admin/workers'
    | '/bruger1/workers'
    | '/bruger2/workers'
    | '/kontaktperson/$id'
    | '/kontaktperson/invite'
    | '/vikar/$id'
    | '/vikar/consent'
    | '/vikar/invite'
    | '/admin'
    | '/bruger1'
    | '/bruger2'
    | '/kontaktperson'
    | '/vikar'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/$id'
    | '/admin/calendar'
    | '/admin/companies'
    | '/admin/create-worker'
    | '/admin/rules'
    | '/admin/statistics'
    | '/admin/users'
    | '/admin/workers'
    | '/bruger1/workers'
    | '/bruger2/workers'
    | '/kontaktperson/$id'
    | '/kontaktperson/invite'
    | '/vikar/$id'
    | '/vikar/consent'
    | '/vikar/invite'
    | '/admin/'
    | '/bruger1/'
    | '/bruger2/'
    | '/kontaktperson/'
    | '/vikar/'
    | '/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminCreateWorkerRoute: typeof AdminCreateWorkerRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWorkersRoute: typeof AdminWorkersRoute
  Bruger1WorkersRoute: typeof Bruger1WorkersRoute
  Bruger2WorkersRoute: typeof Bruger2WorkersRoute
  KontaktpersonIdRoute: typeof KontaktpersonIdRoute
  KontaktpersonInviteRoute: typeof KontaktpersonInviteRoute
  VikarIdRoute: typeof VikarIdRoute
  VikarConsentRoute: typeof VikarConsentRoute
  VikarInviteRoute: typeof VikarInviteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  Bruger1IndexRoute: typeof Bruger1IndexRoute
  Bruger2IndexRoute: typeof Bruger2IndexRoute
  KontaktpersonIndexRoute: typeof KontaktpersonIndexRoute
  VikarIndexRoute: typeof VikarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikar/': {
      id: '/vikar/'
      path: '/vikar'
      fullPath: '/vikar/'
      preLoaderRoute: typeof VikarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktperson/': {
      id: '/kontaktperson/'
      path: '/kontaktperson'
      fullPath: '/kontaktperson/'
      preLoaderRoute: typeof KontaktpersonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruger2/': {
      id: '/bruger2/'
      path: '/bruger2'
      fullPath: '/bruger2/'
      preLoaderRoute: typeof Bruger2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruger1/': {
      id: '/bruger1/'
      path: '/bruger1'
      fullPath: '/bruger1/'
      preLoaderRoute: typeof Bruger1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikar/invite': {
      id: '/vikar/invite'
      path: '/vikar/invite'
      fullPath: '/vikar/invite'
      preLoaderRoute: typeof VikarInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikar/consent': {
      id: '/vikar/consent'
      path: '/vikar/consent'
      fullPath: '/vikar/consent'
      preLoaderRoute: typeof VikarConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikar/$id': {
      id: '/vikar/$id'
      path: '/vikar/$id'
      fullPath: '/vikar/$id'
      preLoaderRoute: typeof VikarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktperson/invite': {
      id: '/kontaktperson/invite'
      path: '/kontaktperson/invite'
      fullPath: '/kontaktperson/invite'
      preLoaderRoute: typeof KontaktpersonInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktperson/$id': {
      id: '/kontaktperson/$id'
      path: '/kontaktperson/$id'
      fullPath: '/kontaktperson/$id'
      preLoaderRoute: typeof KontaktpersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruger2/workers': {
      id: '/bruger2/workers'
      path: '/bruger2/workers'
      fullPath: '/bruger2/workers'
      preLoaderRoute: typeof Bruger2WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruger1/workers': {
      id: '/bruger1/workers'
      path: '/bruger1/workers'
      fullPath: '/bruger1/workers'
      preLoaderRoute: typeof Bruger1WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/admin/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-worker': {
      id: '/admin/create-worker'
      path: '/admin/create-worker'
      fullPath: '/admin/create-worker'
      preLoaderRoute: typeof AdminCreateWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIdRoute: AdminIdRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminCreateWorkerRoute: AdminCreateWorkerRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWorkersRoute: AdminWorkersRoute,
  Bruger1WorkersRoute: Bruger1WorkersRoute,
  Bruger2WorkersRoute: Bruger2WorkersRoute,
  KontaktpersonIdRoute: KontaktpersonIdRoute,
  KontaktpersonInviteRoute: KontaktpersonInviteRoute,
  VikarIdRoute: VikarIdRoute,
  VikarConsentRoute: VikarConsentRoute,
  VikarInviteRoute: VikarInviteRoute,
  AdminIndexRoute: AdminIndexRoute,
  Bruger1IndexRoute: Bruger1IndexRoute,
  Bruger2IndexRoute: Bruger2IndexRoute,
  KontaktpersonIndexRoute: KontaktpersonIndexRoute,
  VikarIndexRoute: VikarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
